# Generated by Django 5.0.3 on 2024-04-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='Article/image')),
                ('create_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=3)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kachka.article')),
            ],
        ),
    ]
