# Generated by Django 5.0.4 on 2024-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kachka', '0002_remove_comment_article_delete_article_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Trainer/')),
                ('facebook', models.CharField(max_length=70)),
                ('intagram', models.CharField(max_length=70)),
                ('twitter', models.CharField(max_length=70)),
            ],
        ),
    ]
